package api

import (
	"bytes"
	"fmt"
	"html"
	"net/http"
	"regexp"
	"sort"
	"strings"
	"sync"

	dedi "github.com/theflywheel/DeDi-node"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	gmhtml "github.com/yuin/goldmark/renderer/html"
)

// The documentation plane: docs/*.md, embedded in the binary and rendered here.
//
// Rendering happens on the server rather than in the reader's browser because
// /docs is the one page that has to work when nothing else does. A client-side
// markdown renderer needs JavaScript to have loaded and run, which is exactly
// what is not true on a locked-down network, in a terminal browser, or for the
// operator reading the page because something is already broken.
//
// The markdown is ours and embedded at build time, so it is trusted input.
// Raw HTML is still left unrendered — see the renderer options below — because
// "trusted" should describe a decision someone made, not a property nobody is
// checking any more once a document gets pasted in from somewhere else.

// doc is one rendered page.
type doc struct {
	Slug    string
	Title   string // the first H1, which every doc in docs/ has
	Summary string // the first paragraph, used on the index
	Body    string // rendered HTML, without the layout
}

// section groups the index. The order is deliberate and hand-written: an index
// generated by listing a directory is alphabetical, and alphabetical order
// tells a reader nothing about where to start. These are ordered the way
// someone actually meets the system — what it is, then how to run it, then how
// to operate it, then how it proves itself, then the specification.
type section struct {
	Name  string
	Intro string
	Slugs []string
}

var sections = []section{
	{"Start here", "What this is, and why it is not a blockchain.",
		[]string{"why", "design"}},
	{"Running a node", "Getting one up, and choosing what it does.",
		[]string{"railway-template", "deployment-modes", "replication"}},
	{"Operating it", "The console, and every write it can make.",
		[]string{"operator-console", "onboarding", "key-rotation", "revocation",
			"delegation", "push", "discovery", "governance"}},
	{"Proving it", "The parts that make a claim checkable by someone who does not trust you.",
		[]string{"witnessing", "file-publication", "conformance"}},
	{"Against the standard", "Where this node and the specification agree, and where they do not.",
		[]string{"reference-schemas", "spec-gaps", "beckn-demo"}},
}

var (
	docsOnce   sync.Once
	docsBySlug map[string]*doc
	docsErr    error
)

// mermaidFence rewrites goldmark's output for a ```mermaid block into the shape
// the pages already use. The explainer page at /docs has rendered diagrams this
// way since before there was a markdown plane, and having two conventions would
// mean a diagram renders or does not depending on which page it landed on.
var mermaidFence = regexp.MustCompile(`(?s)<pre><code class="language-mermaid">(.*?)</code></pre>`)

// The summary shown on the index is taken from the rendered HTML rather than
// the source, so whatever markdown the author used — emphasis, links, code
// spans — arrives as text instead of as syntax.
var (
	paraRe = regexp.MustCompile(`(?s)<p>(.*?)</p>`)
	tagRe  = regexp.MustCompile(`<[^>]*>`)
	h1Re   = regexp.MustCompile(`(?s)<h1[^>]*>(.*?)</h1>`)
	// Several documents open with a provenance block — Status:, Author:, Date:,
	// License:. It is the first paragraph, but it describes the document rather
	// than the subject, and an index built from it tells a reader the authorship
	// of five pages and the topic of none.
	metaPara = regexp.MustCompile(`(?i)^(status|author|date|license|standard of record|companion)\b`)
)

// summarise picks the first paragraph that says what the document is about.
func summarise(body string) string {
	for _, m := range paraRe.FindAllStringSubmatch(body, 8) {
		// Entities are decoded before the caller re-escapes for output.
		// Skipping this step renders a quoted phrase as &amp;quot; on the index,
		// which is the tell that something was escaped twice.
		t := strings.TrimSpace(html.UnescapeString(tagRe.ReplaceAllString(m[1], "")))
		t = strings.Join(strings.Fields(t), " ") // collapse the source's line breaks
		if t == "" || metaPara.MatchString(t) {
			continue
		}
		return clip(t, 190)
	}
	return ""
}

func buildDocs() {
	md := goldmark.New(
		goldmark.WithExtensions(
			extension.GFM,            // tables and strikethrough: the docs use both
			extension.Footnote,       //
			extension.DefinitionList, //
		),
		goldmark.WithParserOptions(
			// Headings get ids so a section can be linked to directly. Without
			// this every reference to a long document has to be "search for".
			parser.WithAutoHeadingID(),
		),
		goldmark.WithRendererOptions(
			// Deliberately NOT WithUnsafe(): raw HTML in the source is escaped
			// rather than passed through. Nothing in docs/ needs it today, and
			// the moment one document does, that should be a decision someone
			// makes on purpose rather than a door that was already open.
			gmhtml.WithXHTML(),
		),
	)

	entries, err := dedi.Docs.ReadDir("docs")
	if err != nil {
		docsErr = fmt.Errorf("read embedded docs: %w", err)
		return
	}

	docsBySlug = make(map[string]*doc, len(entries))
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		src, err := dedi.Docs.ReadFile("docs/" + e.Name())
		if err != nil {
			docsErr = fmt.Errorf("read %s: %w", e.Name(), err)
			return
		}
		var out bytes.Buffer
		if err := md.Convert(src, &out); err != nil {
			docsErr = fmt.Errorf("render %s: %w", e.Name(), err)
			return
		}
		body := mermaidFence.ReplaceAllString(out.String(), `<pre class="mermaid">$1</pre>`)

		d := &doc{
			Slug:  strings.TrimSuffix(e.Name(), ".md"),
			Title: text(h1Re, body),
			Body:  body,
		}
		if d.Title == "" {
			d.Title = d.Slug
		}
		d.Summary = summarise(body)
		docsBySlug[d.Slug] = d
	}
}

func text(re *regexp.Regexp, s string) string {
	m := re.FindStringSubmatch(s)
	if m == nil {
		return ""
	}
	return strings.TrimSpace(html.UnescapeString(tagRe.ReplaceAllString(m[1], "")))
}

// clip shortens at a word boundary. Cutting mid-word on an index reads as a
// truncation bug rather than a summary.
func clip(s string, n int) string {
	if len(s) <= n {
		return s
	}
	if i := strings.LastIndex(s[:n], " "); i > 0 {
		return s[:i] + "…"
	}
	return s[:n] + "…"
}

func loadDocs() (map[string]*doc, error) {
	docsOnce.Do(buildDocs)
	return docsBySlug, docsErr
}

// docIndex is the contents list injected into the explainer page at /docs.
//
// A document present in docs/ but named in no section still appears, under
// "Everything else". Dropping it would mean a page could be written, embedded,
// served at its URL and reachable from nowhere — findable only by someone who
// already knew it existed, which is the one reader who does not need an index.
func (s *Server) docIndex() string {
	docs, err := loadDocs()
	if err != nil || len(docs) == 0 {
		return ""
	}
	listed := map[string]bool{}
	var b strings.Builder

	emit := func(name, intro string, slugs []string) {
		var rows strings.Builder
		for _, slug := range slugs {
			d, ok := docs[slug]
			if !ok {
				continue // named in a section but not written yet
			}
			listed[slug] = true
			rows.WriteString(fmt.Sprintf(
				`<tr><td><a href="/docs/%s">%s</a></td><td class="mut">%s</td></tr>`,
				html.EscapeString(d.Slug), html.EscapeString(d.Title), html.EscapeString(d.Summary)))
		}
		if rows.Len() == 0 {
			return
		}
		b.WriteString("<h3>" + html.EscapeString(name) + "</h3>")
		if intro != "" {
			b.WriteString(`<p class="mut">` + html.EscapeString(intro) + `</p>`)
		}
		b.WriteString("<table>" + rows.String() + "</table>")
	}

	for _, sec := range sections {
		emit(sec.Name, sec.Intro, sec.Slugs)
	}

	var rest []string
	for slug := range docs {
		if !listed[slug] {
			rest = append(rest, slug)
		}
	}
	sort.Strings(rest)
	emit("Everything else", "", rest)

	return b.String()
}

// docPage renders one document at /docs/{page}.
func (s *Server) docPage(w http.ResponseWriter, r *http.Request) {
	docs, err := loadDocs()
	if err != nil {
		internal(w, err)
		return
	}
	d, ok := docs[r.PathValue("page")]
	if !ok {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		w.WriteHeader(http.StatusNotFound)
		fmt.Fprint(w, s.docLayout("Not found",
			`<h1>No such page</h1><p>That document is not part of this node's
			 documentation. <a href="/docs">The contents page</a> lists everything
			 this build ships.</p>`))
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	fmt.Fprint(w, s.docLayout(d.Title, d.Body))
}

// docLayout wraps rendered markdown in the same shell the other embedded pages
// use. The styles are inline for the reason the rest of the node's pages are:
// a documentation page that needs a stylesheet fetch is a page that renders
// unstyled the one time the network is the thing going wrong.
func (s *Server) docLayout(title, body string) string {
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>DeDi Node · ` + html.EscapeString(title) + `</title>
<style>
  body { font-family: monospace; max-width: 68em; margin: 1.5em auto; padding: 0 1em; line-height: 1.55; }
  nav { margin-bottom: 1em; } nav a { margin-right: 1em; }
  nav a.sel { color: inherit; font-weight: bold; text-decoration: none; }
  h1 { font-size: 1.3em; } h2 { font-size: 1.05em; margin: 1.8em 0 .4em; }
  h3 { font-size: .98em; margin: 1.4em 0 .3em; }
  table { border-collapse: collapse; width: 100%; font-size: .92em; margin: .6em 0; }
  th, td { border: 1px solid #ccc; padding: .3em .5em; text-align: left; vertical-align: top; }
  th { background: #f4f4f4; }
  /* Code and tables are the two things that overflow on a phone. Each scrolls
     inside its own box so the page itself never scrolls sideways. */
  pre { overflow-x: auto; background: #f4f4f4; padding: .6em .8em; }
  pre.mermaid { background: #fff; padding: 0; }
  code { background: #f4f4f4; padding: 0 .2em; }
  pre code { background: none; padding: 0; }
  blockquote { border-left: 3px solid #ccc; margin: .8em 0; padding: 0 0 0 .8em; color: #444; }
  .mut { color: #666; }
  .back { margin-top: 2.5em; border-top: 1px solid #ddd; padding-top: .8em; }
</style>
</head>
<body>
` + s.nav("/docs") + `
` + body + `
<p class="back"><a href="/docs">← All documentation</a></p>
` + mermaidRuntime(body) + `</body>
</html>`
}

// mermaidRuntime returns the loader for pages that actually contain a diagram.
//
// Rewriting a ```mermaid fence into <pre class="mermaid"> is only half the job:
// without something to draw it, the block renders as raw diagram source, which
// looks like a broken page rather than a missing script. That is exactly what
// /docs/witnessing shipped as, and the test meant to cover it only asserted the
// fence had been rewritten — it checked the mechanism, not the outcome, so it
// passed while the page was wrong.
//
// Emitted only when there is a diagram, so every other page stays
// dependency-free.
//
// The runtime comes from a CDN, matching the explorer's docs page. That is a
// real dent in this binary's ability to explain itself offline (see embed.go),
// and it is a considered trade rather than an oversight: the prose, which is
// the substance, is embedded and renders with no network at all, and a diagram
// that fails to load degrades to its own source text — readable, being a
// sequence description in something close to English. Vendoring the library
// into every node binary to improve on that is not a trade worth making.
func mermaidRuntime(body string) string {
	if !strings.Contains(body, `<pre class="mermaid">`) {
		return ""
	}
	return `<script type="module">
  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
  mermaid.initialize({ startOnLoad: true, theme: 'neutral', securityLevel: 'strict' });
</script>
`
}
