// Run the shipped verifier against vectors generated by x/mod/sumdb/tlog.
// verify.js is loaded as-is, so this tests the file both pages actually execute.
import { readFileSync } from 'node:fs';
import { webcrypto } from 'node:crypto';
// Node 18 has no global crypto, so it needs filling in; Node 20+ has one and
// defines it as a getter, where assigning throws. Only fill the gap.
if (!globalThis.crypto) globalThis.crypto = webcrypto;

const src = readFileSync(process.argv[3] || 'internal/api/static/verify.js', 'utf8');
const mod = await import('data:text/javascript,' + encodeURIComponent(
  src + '\nexport { checkTree, checkTreeTraced, b64d, eq };'));

const vectors = JSON.parse(readFileSync(process.argv[2], 'utf8'));
let failures = 0;
for (const v of vectors) {
  const proof = (v.proof || []).map(mod.b64d), th = mod.b64d(v.th), h = mod.b64d(v.h);
  let got, traced;
  try { got = await mod.checkTree(proof, v.t, th, v.n, h); }
  catch { got = false; }
  // The traced variant drives the page's "show your work" table. If it ever
  // disagreed with the plain one, the page would narrate a derivation that did
  // not match the verdict beside it.
  try { traced = (await mod.checkTreeTraced(proof, v.t, th, v.n, h, [])).ok; }
  catch { traced = false; }

  const ok = got === v.want && traced === v.want;
  if (!ok) failures++;
  console.log(`  ${ok ? 'PASS' : 'FAIL'}  ${v.name.padEnd(28)} want=${v.want} plain=${got} traced=${traced}`);
}
console.log(failures ? `\n${failures} FAILURES` : '\nplain and traced verifiers both agree with Go');
process.exit(failures ? 1 : 0);
